name: Test terraform-backend-git action
on:
  push:
    branches: [ master ]
jobs:
  build-int:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup terraform-backend-git
        uses: ./.github/actions/setup-terraform-backend-git
        with:
          version: v0.0.14
      - name: Use command
        run: terraform-backend-git version
# @dee-kryvenko this will only work once merged to your repo
#  build-ext:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Setup terraform-backend-git
#        uses: plumber-cd/terraform-backend-git@master
#        with:
#          version: v0.0.14
#      - name: Use command
#        run: terraform-backend-git version